const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let token=localStorage.getItem('linknest-token'),me,links=[],groups=[],view='all',activeGroup=null,query='';
const api=async(path,opts={})=>{let r=await fetch('/api/'+path,{...opts,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...(opts.headers||{})}}),d=await r.json();if(!r.ok)throw Error(d.error||'Ошибка сервера');return d};
const esc=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x])); const initials=x=>x.slice(0,2).toUpperCase();
function switchAuth(x){$('#loginForm').classList.toggle('hidden',x!=='login');$('#registerForm').classList.toggle('hidden',x!=='register')}$$('[data-switch]').forEach(x=>x.onclick=()=>switchAuth(x.dataset.switch));
async function signin(mode,e){e.preventDefault();let username=$(mode==='login'?'#loginUser':'#regUser').value.trim(),password=$(mode==='login'?'#loginPass':'#regPass').value;try{let d=await api('auth/'+mode,{method:'POST',body:JSON.stringify({username,password})});token=d.token;localStorage.setItem('linknest-token',token);await enter()}catch(e){toast(e.message)}}$('#loginForm').onsubmit=e=>signin('login',e);$('#registerForm').onsubmit=e=>signin('register',e);
async function enter(){try{me=(await api('me')).user;$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');$('#profileName').textContent=me.username;$('#avatar').textContent=initials(me.username);await refresh()}catch{localStorage.removeItem('linknest-token');token=null}}
async function refresh(){[links,groups]=await Promise.all([api(view==='shared'?'shared':'links'),api('groups')]);render()}
function render(){let shown=links.filter(l=>(view==='starred'?!l.owner&&l.starred:activeGroup?l.group_id===activeGroup:true)&&(`${l.title} ${l.url}`).toLowerCase().includes(query.toLowerCase()));$('#allCount').textContent=view==='shared'?'':links.length;$('#starCount').textContent=links.filter(x=>x.starred).length;$('#sharedCount').textContent=view==='shared'?links.length:'';$('#pageTitle').textContent=view==='shared'?'Доступные мне':view==='starred'?'Избранное':activeGroup?(groups.find(g=>g.id===activeGroup)?.name||'Коллекция'):'Все ссылки';$('#pageKicker').textContent=view==='shared'?'ОТ ДРУГИХ ПОЛЬЗОВАТЕЛЕЙ':activeGroup?'КОЛЛЕКЦИЯ':'МОЯ БИБЛИОТЕКА';$('#groups').innerHTML=groups.map(g=>`<button class="group-item ${activeGroup===g.id?'active':''}" data-group="${g.id}"><span class="dot" style="background:${g.color}"></span>${esc(g.name)}<em>${g.count}</em></button>`).join('');$$('[data-group]').forEach(b=>b.onclick=()=>{activeGroup=+b.dataset.group;view='all';setActive();refresh()});$('#empty').classList.toggle('hidden',shown.length>0);$('#linkGrid').innerHTML=shown.map(card).join('');$$('.menu').forEach(b=>b.onclick=()=>openMenu(+b.dataset.id,b.dataset.owner));$$('[data-delete]').forEach(b=>b.onclick=async()=>{if(confirm('Удалить эту ссылку?')){try{await api(`links/${b.dataset.delete}`,{method:'DELETE'});await refresh();toast('Ссылка удалена')}catch(e){toast(e.message)}}});}
function card(l){let host;try{host=new URL(l.url).hostname.replace('www.','')}catch{host=l.url}return `<article class="card"><div class="card-top"><div class="favicon">${esc(l.icon||'↗')}</div><div>${!l.owner?`<button class="delete-link" title="Удалить" data-delete="${l.id}">−</button>`:''}<button class="menu" data-id="${l.id}" data-owner="${esc(l.owner||'')}">⋯</button></div></div><h3>${esc(l.title)}</h3><div class="url">${esc(host)}</div><div class="tags"><span class="tag">${esc(l.group_name||'Без группы')}</span>${l.owner?`<span class="shared-note">от ${esc(l.owner)}</span>`:`<span class="privacy">${l.share_count?'◌':'⌁'}</span>`}</div></article>`}
function setActive(){$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view))}$$('.nav-item').forEach(b=>b.onclick=()=>{view=b.dataset.view;activeGroup=null;setActive();refresh()});$('#search').oninput=e=>{query=e.target.value;render()};$('#addLink').onclick=addModal;$('#logout').onclick=()=>{localStorage.removeItem('linknest-token');location.reload()};
function modal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden')}function close(){$('#modal').classList.add('hidden')} $('[data-close]').onclick=close;$('#modal').onclick=e=>{if(e.target===$('#modal'))close()};
function addModal(){modal(`<h2>Новая ссылка</h2><p class="intro">Она будет приватной — доступ появится только у тех, с кем вы ею поделитесь.</p><form id="linkForm"><label>Название<input id="fTitle" required placeholder="Например, Подборка книг"></label><label>Ссылка<input id="fUrl" required placeholder="example.com или https://example.com"></label><div class="form-row"><label>Коллекция<select id="fGroup"><option value="">Без группы</option>${groups.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('')}</select></label><label>Значок<input id="fIcon" maxlength="2" value="↗"></label></div><button class="primary">Сохранить ссылку <span>→</span></button></form>`);$('#linkForm').onsubmit=async e=>{e.preventDefault();try{let url=$('#fUrl').value.trim();if(!/^https?:\/\//i.test(url))url='https://'+url;await api('links',{method:'POST',body:JSON.stringify({title:$('#fTitle').value,url,icon:$('#fIcon').value,group_id:$('#fGroup').value||null})});close();await refresh();toast('Ссылка сохранена')}catch(e){toast(e.message)}}}
function groupModal(){modal(`<h2>Новая коллекция</h2><p class="intro">Соберите ссылки под одним понятным названием.</p><form id="groupForm"><label>Название коллекции<input id="gName" required placeholder="Например, Путешествия"></label><button class="primary">Создать коллекцию <span>→</span></button></form>`);$('#groupForm').onsubmit=async e=>{e.preventDefault();try{await api('groups',{method:'POST',body:JSON.stringify({name:$('#gName').value})});close();await refresh();toast('Коллекция создана')}catch(e){toast(e.message)}}}
async function openMenu(id,owner){let l=links.find(x=>x.id===id);if(owner){modal(`<h2>${esc(owner)} поделился(ась)</h2><p class="intro">Эта ссылка доступна вам, пока владелец не отзовёт доступ.</p><a class="primary wide" href="${esc(l.url)}" target="_blank" style="display:block;text-align:center;text-decoration:none">Открыть ссылку ↗</a>`);return}let shares=await api(`links/${id}/shares`);modal(`<h2>${esc(l.title)}</h2><p class="intro">Управляйте доступом к этой ссылке.</p><div class="share-list">${shares.length?shares.map(x=>`<span class="share-chip">${esc(x.username)}<button data-unshare="${esc(x.username)}">×</button></span>`).join(''):'<span class="intro">Пока только вы видите эту ссылку.</span>'}</div><form id="shareForm" style="margin-top:18px"><label>Поделиться с пользователем<input id="shareUser" placeholder="Имя пользователя"></label><button class="primary">Открыть доступ <span>→</span></button></form><button id="toggleStar" class="text-btn" style="margin-top:16px">${l.starred?'Убрать из избранного':'Добавить в избранное'}</button>`);$$('[data-unshare]').forEach(b=>b.onclick=async()=>{await api(`links/${id}/shares/${b.dataset.unshare}`,{method:'DELETE'});await openMenu(id);refresh()});$('#shareForm').onsubmit=async e=>{e.preventDefault();try{await api(`links/${id}/shares`,{method:'POST',body:JSON.stringify({username:$('#shareUser').value})});close();await refresh();toast('Доступ открыт')}catch(e){toast(e.message)}};$('#toggleStar').onclick=async()=>{await api(`links/${id}`,{method:'PATCH',body:JSON.stringify({starred:!l.starred})});close();refresh()}}
function toast(t){let x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2400)}if(token)enter();
